
platform :ios, '8.0'
 

target 'FlagShip_Example' do
  pod 'FlagShip', :path => '../'
  
  target 'FlagShip_Tests' do
    inherit! :search_paths

  end
end

target 'objcExample' do
  use_frameworks!
  pod 'FlagShip', :path => '../'
end

