use_frameworks!


target 'FlagShipSdk' do
    pod 'ReachabilitySwift'
    end
target 'FlagShip_Example' do
  pod 'FlagShip', :path => '../'
  
  target 'FlagShip_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
